export type Locale = "en" | "fr" | "de" | "it" | "es";
export const supportedLocales: Locale[] = ["en", "fr", "de", "it", "es"];
export const localeLabels: Record<Locale, string> = { en: "English", fr: "Francais", de: "Deutsch", it: "Italiano", es: "Espanol" };

type Tabs<T extends string> = Record<T, string>;
type MessageSet = {
  eyebrow: string; title: string; subtitle: string; banner: string; languageLabel: string; refresh: string; loading: string; noData: string; saved: string; create: string; save: string; search: string; enabled: string; disabled: string; close: string; open: string; newItem: string; loginTitle: string; loginHelp: string; login: string; logout: string; password: string; runPstJobs: string; oidcLogin: string; oidcOrDivider: string;
  pageServer: string; pageDomain: string; pageAntispam: string; pageAudit: string; pageOperations: string;
  serverTabs: Tabs<"status"|"server"|"security"|"ai"|"domains"|"admins">;
  domainTabs: Tabs<"overview"|"accounts"|"aliases"|"admins">;
  antispamTabs: Tabs<"content"|"engines"|"rules"|"quarantine">;
  auditTabs: Tabs<"journal"|"trace">;
  operationsTabs: Tabs<"protocols"|"storage"|"mailflow">;
  serverOverview: string; protocolStatus: string; serverPolicies: string; securityPolicies: string; localAiPolicies: string; manageDomains: string; administrators: string; adminMatrix: string; selectedDomain: string; domainPolicySnapshot: string; domainAccounts: string; domainAliases: string; domainAdmins: string; contentFiltering: string; antispamEngines: string; filterRules: string; ruleList: string; quarantine: string; auditJournal: string; emailTrace: string; storageOverview: string; mailFlowMonitor: string; mailboxTransfers: string; pstImport: string; pstExport: string; pstPath: string; pstFile: string; requestedBy: string; transferHistory: string; noTransfers: string; mailboxName: string; accountDetails: string; newAccount: string; newPassword: string; primaryMailbox: string; selectAccountHint: string;
  domains: string; accounts: string; aliases: string; queue: string; status: string; defaultQuota: string; inbound: string; outbound: string; hostname: string; defaultLocale: string; adminBind: string; smtpBind: string; imapBind: string; jmapBind: string; maxMessage: string; tlsMode: string; passwordLogin: string; mfa: string; sessionTimeout: string; auditRetention: string; aiEnabled: string; offlineOnly: string; indexing: string; provider: string; model: string; domainName: string; adminEmail: string; displayName: string; role: string; rights: string; permissions: string; localPart: string; quota: string; source: string; target: string; kind: string; spamEngine: string; quarantineRetention: string; ruleName: string; scope: string; action: string; searchQuery: string; domainList: string; primaryStore: string; searchEngine: string; replication: string; galVisibility: string; directoryKind: string; defaultSieveScript: string; mailFlowStatus: string; queueOwner: string; lastAttempt: string; nextAttempt: string; oidcEnabled: string; oidcProviderLabel: string; oidcAutoLink: string; oidcIssuerUrl: string; oidcAuthorizationEndpoint: string; oidcTokenEndpoint: string; oidcUserinfoEndpoint: string; oidcClientId: string; oidcClientSecret: string; oidcScopes: string; oidcClaimEmail: string; oidcClaimDisplayName: string; oidcClaimSubject: string;
};
const en: MessageSet = {
  eyebrow: "La Poste Electronique", title: "Admin Console", subtitle: "Structured administration for server, domains, anti-spam, audit, and operations.", banner: "Server-first and domain-first navigation for the control plane.", languageLabel: "Language", refresh: "Refresh", loading: "Loading...", noData: "No data yet.", saved: "Saved.", create: "Create", save: "Save", search: "Search", enabled: "Enabled", disabled: "Disabled", close: "Close", open: "Open", newItem: "New", loginTitle: "Admin sign in", loginHelp: "Use an administrator account to access the control plane.", login: "Sign in", logout: "Sign out", password: "Password", runPstJobs: "Run pending PST jobs", oidcLogin: "Sign in with SSO", oidcOrDivider: "or",
  pageServer: "Server", pageDomain: "Domain", pageAntispam: "Anti-Spam", pageAudit: "Audit", pageOperations: "Operations",
  serverTabs: { status: "Status", server: "Server Policies", security: "Security Policies", ai: "Local AI Policies", domains: "Domains", admins: "Administrators" },
  domainTabs: { overview: "Overview", accounts: "Accounts", aliases: "Aliases", admins: "Admins" },
  antispamTabs: { content: "Content Filtering", engines: "Anti-Spam Engines", rules: "Filter Rules", quarantine: "Quarantine" },
  auditTabs: { journal: "Journal", trace: "Email Trace" },
  operationsTabs: { protocols: "Protocols", storage: "Storage", mailflow: "Mail Flow" },
  serverOverview: "Server overview", protocolStatus: "Protocol status", serverPolicies: "Server policies", securityPolicies: "Security policies", localAiPolicies: "Local AI policies", manageDomains: "Manage domains", administrators: "Administrators", adminMatrix: "Admin rights by domain", selectedDomain: "Selected domain", domainPolicySnapshot: "Domain policy snapshot", domainAccounts: "Accounts in domain", domainAliases: "Aliases in domain", domainAdmins: "Domain administrators", contentFiltering: "Content filtering", antispamEngines: "Anti-spam engines", filterRules: "Filter rules", ruleList: "Rules list", quarantine: "Quarantine", auditJournal: "Audit journal", emailTrace: "Multi-criteria email trace search", storageOverview: "Storage overview", mailFlowMonitor: "Mail flow monitor", mailboxTransfers: "Mailbox PST transfers", pstImport: "Import PST", pstExport: "Export PST", pstPath: "Server PST path", pstFile: "PST file", requestedBy: "Requested by", transferHistory: "Transfer history", noTransfers: "No PST transfer yet.", mailboxName: "Mailbox", accountDetails: "Account details", newAccount: "New", newPassword: "New password", primaryMailbox: "Primary mailbox", selectAccountHint: "Double-click an account, or use import/export from the account list.",
  domains: "Domains", accounts: "Accounts", aliases: "Aliases", queue: "Queues", status: "Status", defaultQuota: "Default quota", inbound: "Inbound", outbound: "Outbound", hostname: "Primary hostname", defaultLocale: "Default locale", adminBind: "Admin API bind", smtpBind: "SMTP bind", imapBind: "IMAP bind", jmapBind: "JMAP bind", maxMessage: "Max message size (MB)", tlsMode: "TLS mode", passwordLogin: "Password login", mfa: "MFA required", sessionTimeout: "Session timeout (min)", auditRetention: "Audit retention (days)", aiEnabled: "Local AI enabled", offlineOnly: "Offline only", indexing: "Attachment indexing", provider: "Provider", model: "Model", domainName: "Domain name", adminEmail: "Admin email", displayName: "Display name", role: "Role", rights: "Rights summary", permissions: "Permissions", localPart: "Local part", quota: "Quota (MB)", source: "Source", target: "Target", kind: "Kind", spamEngine: "Spam engine", quarantineRetention: "Quarantine retention (days)", ruleName: "Rule name", scope: "Scope", action: "Action", searchQuery: "Query", domainList: "Domain list", primaryStore: "Primary store", searchEngine: "Search engine", replication: "Replication", galVisibility: "GAL visibility", directoryKind: "Directory kind", defaultSieveScript: "Default Sieve script", mailFlowStatus: "Delivery state", queueOwner: "Queue owner", lastAttempt: "Last attempt", nextAttempt: "Next attempt", oidcEnabled: "OIDC login", oidcProviderLabel: "OIDC provider label", oidcAutoLink: "Auto-link by email", oidcIssuerUrl: "OIDC issuer URL", oidcAuthorizationEndpoint: "Authorization endpoint", oidcTokenEndpoint: "Token endpoint", oidcUserinfoEndpoint: "Userinfo endpoint", oidcClientId: "OIDC client ID", oidcClientSecret: "OIDC client secret", oidcScopes: "OIDC scopes", oidcClaimEmail: "Email claim", oidcClaimDisplayName: "Display name claim", oidcClaimSubject: "Subject claim"
};
export const messages: Record<Locale, MessageSet> = { en, fr: en, de: en, it: en, es: en };
export function getInitialLocale(): Locale { if (typeof window === "undefined") return "en"; const stored = window.localStorage.getItem("lpe.locale"); return stored && supportedLocales.includes(stored as Locale) ? stored as Locale : "en"; }
