import {
  defineLocaleCatalog,
  getInitialLocale,
  localeLabels,
  setStoredLocale,
  supportedLocales,
  type Locale,
} from "../../shared/src/i18n";

export { getInitialLocale, localeLabels, setStoredLocale, supportedLocales, type Locale };

type Tabs<T extends string> = Record<T, string>;
type MessageSet = {
  eyebrow: string; title: string; subtitle: string; banner: string; languageLabel: string; refresh: string; loading: string; noData: string; saved: string; create: string; save: string; search: string; enabled: string; disabled: string; close: string; open: string; newItem: string; loginTitle: string; loginHelp: string; login: string; logout: string; password: string; runPstJobs: string; oidcLogin: string; oidcOrDivider: string;
  pageServer: string; pageDomain: string; pageAntispam: string; pageAudit: string; pageOperations: string;
  serverTabs: Tabs<"status"|"server"|"security"|"ai"|"domains"|"admins">;
  domainTabs: Tabs<"overview"|"accounts"|"aliases"|"admins">;
  antispamTabs: Tabs<"content"|"engines"|"rules"|"quarantine">;
  auditTabs: Tabs<"journal"|"trace">;
  operationsTabs: Tabs<"protocols"|"storage"|"mailflow">;
  serverOverview: string; protocolStatus: string; serverPolicies: string; securityPolicies: string; localAiPolicies: string; manageDomains: string; administrators: string; adminMatrix: string; selectedDomain: string; domainPolicySnapshot: string; domainAccounts: string; domainAliases: string; domainAdmins: string; contentFiltering: string; antispamEngines: string; filterRules: string; ruleList: string; quarantine: string; auditJournal: string; emailTrace: string; storageOverview: string; mailFlowMonitor: string; mailboxTransfers: string; pstImport: string; pstExport: string; pstPath: string; pstFile: string; requestedBy: string; transferHistory: string; noTransfers: string; mailboxName: string; accountDetails: string; newAccount: string; newPassword: string; primaryMailbox: string; selectAccountHint: string;
  domains: string; accounts: string; aliases: string; queue: string; status: string; defaultQuota: string; inbound: string; outbound: string; hostname: string; defaultLocale: string; adminBind: string; smtpBind: string; imapBind: string; jmapBind: string; maxMessage: string; tlsMode: string; passwordLogin: string; mfa: string; sessionTimeout: string; auditRetention: string; aiEnabled: string; offlineOnly: string; indexing: string; provider: string; model: string; domainName: string; adminEmail: string; displayName: string; role: string; rights: string; permissions: string; localPart: string; quota: string; source: string; target: string; kind: string; spamEngine: string; quarantineRetention: string; ruleName: string; scope: string; action: string; searchQuery: string; domainList: string; primaryStore: string; searchEngine: string; replication: string; galVisibility: string; directoryKind: string; defaultSieveScript: string; mailFlowStatus: string; queueOwner: string; lastAttempt: string; nextAttempt: string; oidcEnabled: string; oidcProviderLabel: string; oidcAutoLink: string; oidcIssuerUrl: string; oidcAuthorizationEndpoint: string; oidcTokenEndpoint: string; oidcUserinfoEndpoint: string; oidcClientId: string; oidcClientSecret: string; oidcScopes: string; oidcClaimEmail: string; oidcClaimDisplayName: string; oidcClaimSubject: string;
};
const en: MessageSet = {
  eyebrow: "La Poste Electronique", title: "Admin Console", subtitle: "Structured administration for server, domains, anti-spam, audit, and operations.", banner: "Server-first and domain-first navigation for the control plane.", languageLabel: "Language", refresh: "Refresh", loading: "Loading...", noData: "No data yet.", saved: "Saved.", create: "Create", save: "Save", search: "Search", enabled: "Enabled", disabled: "Disabled", close: "Close", open: "Open", newItem: "New", loginTitle: "Admin sign in", loginHelp: "Use an administrator account to access the control plane.", login: "Sign in", logout: "Sign out", password: "Password", runPstJobs: "Run pending PST jobs", oidcLogin: "Sign in with SSO", oidcOrDivider: "or",
  pageServer: "Server", pageDomain: "Domain", pageAntispam: "Anti-Spam", pageAudit: "Audit", pageOperations: "Operations",
  serverTabs: { status: "Status", server: "Server Policies", security: "Security Policies", ai: "Local AI Policies", domains: "Domains", admins: "Administrators" },
  domainTabs: { overview: "Overview", accounts: "Accounts", aliases: "Aliases", admins: "Admins" },
  antispamTabs: { content: "Content Filtering", engines: "Anti-Spam Engines", rules: "Filter Rules", quarantine: "Quarantine" },
  auditTabs: { journal: "Journal", trace: "Email Trace" },
  operationsTabs: { protocols: "Protocols", storage: "Storage", mailflow: "Mail Flow" },
  serverOverview: "Server overview", protocolStatus: "Protocol status", serverPolicies: "Server policies", securityPolicies: "Security policies", localAiPolicies: "Local AI policies", manageDomains: "Manage domains", administrators: "Administrators", adminMatrix: "Admin rights by domain", selectedDomain: "Selected domain", domainPolicySnapshot: "Domain policy snapshot", domainAccounts: "Accounts in domain", domainAliases: "Aliases in domain", domainAdmins: "Domain administrators", contentFiltering: "Content filtering", antispamEngines: "Anti-spam engines", filterRules: "Filter rules", ruleList: "Rules list", quarantine: "Quarantine", auditJournal: "Audit journal", emailTrace: "Multi-criteria email trace search", storageOverview: "Storage overview", mailFlowMonitor: "Mail flow monitor", mailboxTransfers: "Mailbox PST transfers", pstImport: "Import PST", pstExport: "Export PST", pstPath: "Server PST path", pstFile: "PST file", requestedBy: "Requested by", transferHistory: "Transfer history", noTransfers: "No PST transfer yet.", mailboxName: "Mailbox", accountDetails: "Account details", newAccount: "New", newPassword: "New password", primaryMailbox: "Primary mailbox", selectAccountHint: "Double-click an account, or use import/export from the account list.",
  domains: "Domains", accounts: "Accounts", aliases: "Aliases", queue: "Queues", status: "Status", defaultQuota: "Default quota", inbound: "Inbound", outbound: "Outbound", hostname: "Primary hostname", defaultLocale: "Default locale", adminBind: "Admin API bind", smtpBind: "SMTP bind", imapBind: "IMAP bind", jmapBind: "JMAP bind", maxMessage: "Max message size (MB)", tlsMode: "TLS mode", passwordLogin: "Password login", mfa: "MFA required", sessionTimeout: "Session timeout (min)", auditRetention: "Audit retention (days)", aiEnabled: "Local AI enabled", offlineOnly: "Offline only", indexing: "Attachment indexing", provider: "Provider", model: "Model", domainName: "Domain name", adminEmail: "Admin email", displayName: "Display name", role: "Role", rights: "Rights summary", permissions: "Permissions", localPart: "Local part", quota: "Quota (MB)", source: "Source", target: "Target", kind: "Kind", spamEngine: "Spam engine", quarantineRetention: "Quarantine retention (days)", ruleName: "Rule name", scope: "Scope", action: "Action", searchQuery: "Query", domainList: "Domain list", primaryStore: "Primary store", searchEngine: "Search engine", replication: "Replication", galVisibility: "GAL visibility", directoryKind: "Directory kind", defaultSieveScript: "Default Sieve script", mailFlowStatus: "Delivery state", queueOwner: "Queue owner", lastAttempt: "Last attempt", nextAttempt: "Next attempt", oidcEnabled: "OIDC login", oidcProviderLabel: "OIDC provider label", oidcAutoLink: "Auto-link by email", oidcIssuerUrl: "OIDC issuer URL", oidcAuthorizationEndpoint: "Authorization endpoint", oidcTokenEndpoint: "Token endpoint", oidcUserinfoEndpoint: "Userinfo endpoint", oidcClientId: "OIDC client ID", oidcClientSecret: "OIDC client secret", oidcScopes: "OIDC scopes", oidcClaimEmail: "Email claim", oidcClaimDisplayName: "Display name claim", oidcClaimSubject: "Subject claim"
};

const fr: MessageSet = {
  eyebrow: "La Poste Electronique", title: "Console d'administration", subtitle: "Administration structuree du serveur, des domaines, de l'anti-spam, de l'audit et des operations.", banner: "Navigation d'abord serveur et domaine pour le plan de controle.", languageLabel: "Langue", refresh: "Actualiser", loading: "Chargement...", noData: "Pas encore de donnees.", saved: "Enregistre.", create: "Creer", save: "Enregistrer", search: "Rechercher", enabled: "Active", disabled: "Desactive", close: "Fermer", open: "Ouvrir", newItem: "Nouveau", loginTitle: "Connexion administrateur", loginHelp: "Utilise un compte administrateur pour acceder au plan de controle.", login: "Se connecter", logout: "Se deconnecter", password: "Mot de passe", runPstJobs: "Executer les taches PST en attente", oidcLogin: "Se connecter avec SSO", oidcOrDivider: "ou",
  pageServer: "Serveur", pageDomain: "Domaine", pageAntispam: "Anti-spam", pageAudit: "Audit", pageOperations: "Operations",
  serverTabs: { status: "Statut", server: "Politiques serveur", security: "Politiques de securite", ai: "Politiques IA locale", domains: "Domaines", admins: "Administrateurs" },
  domainTabs: { overview: "Vue d'ensemble", accounts: "Comptes", aliases: "Alias", admins: "Admins" },
  antispamTabs: { content: "Filtrage de contenu", engines: "Moteurs anti-spam", rules: "Regles de filtrage", quarantine: "Quarantaine" },
  auditTabs: { journal: "Journal", trace: "Trace email" },
  operationsTabs: { protocols: "Protocoles", storage: "Stockage", mailflow: "Flux mail" },
  serverOverview: "Vue d'ensemble du serveur", protocolStatus: "Statut des protocoles", serverPolicies: "Politiques serveur", securityPolicies: "Politiques de securite", localAiPolicies: "Politiques IA locale", manageDomains: "Gerer les domaines", administrators: "Administrateurs", adminMatrix: "Droits admin par domaine", selectedDomain: "Domaine selectionne", domainPolicySnapshot: "Capture des politiques du domaine", domainAccounts: "Comptes du domaine", domainAliases: "Alias du domaine", domainAdmins: "Administrateurs du domaine", contentFiltering: "Filtrage de contenu", antispamEngines: "Moteurs anti-spam", filterRules: "Regles de filtrage", ruleList: "Liste des regles", quarantine: "Quarantaine", auditJournal: "Journal d'audit", emailTrace: "Recherche multi-criteres de trace email", storageOverview: "Vue d'ensemble du stockage", mailFlowMonitor: "Supervision du flux mail", mailboxTransfers: "Transferts PST des boites", pstImport: "Importer PST", pstExport: "Exporter PST", pstPath: "Chemin PST serveur", pstFile: "Fichier PST", requestedBy: "Demande par", transferHistory: "Historique des transferts", noTransfers: "Aucun transfert PST pour l'instant.", mailboxName: "Boite", accountDetails: "Details du compte", newAccount: "Nouveau", newPassword: "Nouveau mot de passe", primaryMailbox: "Boite principale", selectAccountHint: "Double-clique un compte ou utilise import/export depuis la liste des comptes.",
  domains: "Domaines", accounts: "Comptes", aliases: "Alias", queue: "Files", status: "Statut", defaultQuota: "Quota par defaut", inbound: "Entrant", outbound: "Sortant", hostname: "Nom d'hote principal", defaultLocale: "Locale par defaut", adminBind: "Bind API admin", smtpBind: "Bind SMTP", imapBind: "Bind IMAP", jmapBind: "Bind JMAP", maxMessage: "Taille max du message (MB)", tlsMode: "Mode TLS", passwordLogin: "Connexion par mot de passe", mfa: "MFA requise", sessionTimeout: "Expiration de session (min)", auditRetention: "Retention d'audit (jours)", aiEnabled: "IA locale activee", offlineOnly: "Hors ligne uniquement", indexing: "Indexation des pieces jointes", provider: "Fournisseur", model: "Modele", domainName: "Nom de domaine", adminEmail: "Email admin", displayName: "Nom d'affichage", role: "Role", rights: "Resume des droits", permissions: "Permissions", localPart: "Partie locale", quota: "Quota (MB)", source: "Source", target: "Cible", kind: "Type", spamEngine: "Moteur spam", quarantineRetention: "Retention de quarantaine (jours)", ruleName: "Nom de la regle", scope: "Portee", action: "Action", searchQuery: "Requete", domainList: "Liste des domaines", primaryStore: "Stockage principal", searchEngine: "Moteur de recherche", replication: "Replication", galVisibility: "Visibilite GAL", directoryKind: "Type d'annuaire", defaultSieveScript: "Script Sieve par defaut", mailFlowStatus: "Etat de livraison", queueOwner: "Proprietaire de la file", lastAttempt: "Derniere tentative", nextAttempt: "Prochaine tentative", oidcEnabled: "Connexion OIDC", oidcProviderLabel: "Libelle du fournisseur OIDC", oidcAutoLink: "Liaison automatique par email", oidcIssuerUrl: "URL issuer OIDC", oidcAuthorizationEndpoint: "Point d'autorisation", oidcTokenEndpoint: "Point token", oidcUserinfoEndpoint: "Point userinfo", oidcClientId: "ID client OIDC", oidcClientSecret: "Secret client OIDC", oidcScopes: "Scopes OIDC", oidcClaimEmail: "Claim email", oidcClaimDisplayName: "Claim nom d'affichage", oidcClaimSubject: "Claim sujet"
};

const de: MessageSet = {
  eyebrow: "La Poste Electronique", title: "Admin-Konsole", subtitle: "Strukturierte Verwaltung fur Server, Domains, Anti-Spam, Audit und Betrieb.", banner: "Server- und domainorientierte Navigation fur die Steuerungsebene.", languageLabel: "Sprache", refresh: "Aktualisieren", loading: "Laden...", noData: "Noch keine Daten.", saved: "Gespeichert.", create: "Erstellen", save: "Speichern", search: "Suchen", enabled: "Aktiviert", disabled: "Deaktiviert", close: "Schliessen", open: "Offnen", newItem: "Neu", loginTitle: "Admin-Anmeldung", loginHelp: "Verwende ein Administratorkonto fur den Zugriff auf die Steuerungsebene.", login: "Anmelden", logout: "Abmelden", password: "Passwort", runPstJobs: "Ausstehende PST-Jobs ausfuhren", oidcLogin: "Mit SSO anmelden", oidcOrDivider: "oder",
  pageServer: "Server", pageDomain: "Domain", pageAntispam: "Anti-Spam", pageAudit: "Audit", pageOperations: "Betrieb",
  serverTabs: { status: "Status", server: "Server-Richtlinien", security: "Sicherheitsrichtlinien", ai: "Lokale KI-Richtlinien", domains: "Domains", admins: "Administratoren" },
  domainTabs: { overview: "Ubersicht", accounts: "Konten", aliases: "Aliase", admins: "Admins" },
  antispamTabs: { content: "Inhaltsfilterung", engines: "Anti-Spam-Engines", rules: "Filterregeln", quarantine: "Quarantane" },
  auditTabs: { journal: "Journal", trace: "E-Mail-Trace" },
  operationsTabs: { protocols: "Protokolle", storage: "Speicher", mailflow: "Mail-Fluss" },
  serverOverview: "Server-Ubersicht", protocolStatus: "Protokollstatus", serverPolicies: "Server-Richtlinien", securityPolicies: "Sicherheitsrichtlinien", localAiPolicies: "Lokale KI-Richtlinien", manageDomains: "Domains verwalten", administrators: "Administratoren", adminMatrix: "Admin-Rechte nach Domain", selectedDomain: "Ausgewahlte Domain", domainPolicySnapshot: "Domain-Richtlinienstand", domainAccounts: "Konten in der Domain", domainAliases: "Aliase in der Domain", domainAdmins: "Domain-Administratoren", contentFiltering: "Inhaltsfilterung", antispamEngines: "Anti-Spam-Engines", filterRules: "Filterregeln", ruleList: "Regelliste", quarantine: "Quarantane", auditJournal: "Audit-Journal", emailTrace: "Mehrkriterielle E-Mail-Trace-Suche", storageOverview: "Speicherubersicht", mailFlowMonitor: "Mail-Fluss-Monitor", mailboxTransfers: "PST-Transfers der Postfacher", pstImport: "PST importieren", pstExport: "PST exportieren", pstPath: "PST-Serverpfad", pstFile: "PST-Datei", requestedBy: "Angefordert von", transferHistory: "Transferverlauf", noTransfers: "Noch kein PST-Transfer.", mailboxName: "Postfach", accountDetails: "Kontodetails", newAccount: "Neu", newPassword: "Neues Passwort", primaryMailbox: "Primare Mailbox", selectAccountHint: "Doppelklicke auf ein Konto oder nutze Import/Export aus der Kontoliste.",
  domains: "Domains", accounts: "Konten", aliases: "Aliase", queue: "Warteschlangen", status: "Status", defaultQuota: "Standard-Quota", inbound: "Eingehend", outbound: "Ausgehend", hostname: "Primarer Hostname", defaultLocale: "Standard-Locale", adminBind: "Admin-API-Bind", smtpBind: "SMTP-Bind", imapBind: "IMAP-Bind", jmapBind: "JMAP-Bind", maxMessage: "Maximale Nachrichtengrosse (MB)", tlsMode: "TLS-Modus", passwordLogin: "Passwort-Anmeldung", mfa: "MFA erforderlich", sessionTimeout: "Sitzungszeitlimit (Min)", auditRetention: "Audit-Aufbewahrung (Tage)", aiEnabled: "Lokale KI aktiviert", offlineOnly: "Nur offline", indexing: "Anhang-Indexierung", provider: "Anbieter", model: "Modell", domainName: "Domainname", adminEmail: "Admin-E-Mail", displayName: "Anzeigename", role: "Rolle", rights: "Rechteubersicht", permissions: "Berechtigungen", localPart: "Lokaler Teil", quota: "Quota (MB)", source: "Quelle", target: "Ziel", kind: "Art", spamEngine: "Spam-Engine", quarantineRetention: "Quarantane-Aufbewahrung (Tage)", ruleName: "Regelname", scope: "Bereich", action: "Aktion", searchQuery: "Abfrage", domainList: "Domainliste", primaryStore: "Primarspeicher", searchEngine: "Suchmaschine", replication: "Replikation", galVisibility: "GAL-Sichtbarkeit", directoryKind: "Verzeichnisart", defaultSieveScript: "Standard-Sieve-Skript", mailFlowStatus: "Zustellstatus", queueOwner: "Eigentumer der Warteschlange", lastAttempt: "Letzter Versuch", nextAttempt: "Nachster Versuch", oidcEnabled: "OIDC-Anmeldung", oidcProviderLabel: "OIDC-Anbieterbezeichnung", oidcAutoLink: "Automatische Verknupfung per E-Mail", oidcIssuerUrl: "OIDC-Issuer-URL", oidcAuthorizationEndpoint: "Autorisierungsendpunkt", oidcTokenEndpoint: "Token-Endpunkt", oidcUserinfoEndpoint: "Userinfo-Endpunkt", oidcClientId: "OIDC-Client-ID", oidcClientSecret: "OIDC-Client-Secret", oidcScopes: "OIDC-Scopes", oidcClaimEmail: "E-Mail-Claim", oidcClaimDisplayName: "Anzeigename-Claim", oidcClaimSubject: "Subject-Claim"
};

const it: MessageSet = {
  eyebrow: "La Poste Electronique", title: "Console di amministrazione", subtitle: "Amministrazione strutturata per server, domini, anti-spam, audit e operazioni.", banner: "Navigazione centrata su server e domini per il piano di controllo.", languageLabel: "Lingua", refresh: "Aggiorna", loading: "Caricamento...", noData: "Nessun dato ancora.", saved: "Salvato.", create: "Crea", save: "Salva", search: "Cerca", enabled: "Abilitato", disabled: "Disabilitato", close: "Chiudi", open: "Apri", newItem: "Nuovo", loginTitle: "Accesso amministratore", loginHelp: "Usa un account amministratore per accedere al piano di controllo.", login: "Accedi", logout: "Disconnetti", password: "Password", runPstJobs: "Esegui i job PST in attesa", oidcLogin: "Accedi con SSO", oidcOrDivider: "oppure",
  pageServer: "Server", pageDomain: "Dominio", pageAntispam: "Anti-spam", pageAudit: "Audit", pageOperations: "Operazioni",
  serverTabs: { status: "Stato", server: "Politiche server", security: "Politiche di sicurezza", ai: "Politiche IA locale", domains: "Domini", admins: "Amministratori" },
  domainTabs: { overview: "Panoramica", accounts: "Account", aliases: "Alias", admins: "Admin" },
  antispamTabs: { content: "Filtro contenuti", engines: "Motori anti-spam", rules: "Regole filtro", quarantine: "Quarantena" },
  auditTabs: { journal: "Registro", trace: "Traccia email" },
  operationsTabs: { protocols: "Protocolli", storage: "Storage", mailflow: "Flusso mail" },
  serverOverview: "Panoramica server", protocolStatus: "Stato protocolli", serverPolicies: "Politiche server", securityPolicies: "Politiche di sicurezza", localAiPolicies: "Politiche IA locale", manageDomains: "Gestisci domini", administrators: "Amministratori", adminMatrix: "Diritti admin per dominio", selectedDomain: "Dominio selezionato", domainPolicySnapshot: "Stato politiche dominio", domainAccounts: "Account del dominio", domainAliases: "Alias del dominio", domainAdmins: "Amministratori del dominio", contentFiltering: "Filtro contenuti", antispamEngines: "Motori anti-spam", filterRules: "Regole filtro", ruleList: "Elenco regole", quarantine: "Quarantena", auditJournal: "Registro audit", emailTrace: "Ricerca traccia email multi-criterio", storageOverview: "Panoramica storage", mailFlowMonitor: "Monitor flusso mail", mailboxTransfers: "Trasferimenti PST delle mailbox", pstImport: "Importa PST", pstExport: "Esporta PST", pstPath: "Percorso PST server", pstFile: "File PST", requestedBy: "Richiesto da", transferHistory: "Cronologia trasferimenti", noTransfers: "Nessun trasferimento PST ancora.", mailboxName: "Mailbox", accountDetails: "Dettagli account", newAccount: "Nuovo", newPassword: "Nuova password", primaryMailbox: "Mailbox primaria", selectAccountHint: "Fai doppio clic su un account oppure usa import/export dall'elenco account.",
  domains: "Domini", accounts: "Account", aliases: "Alias", queue: "Code", status: "Stato", defaultQuota: "Quota predefinita", inbound: "Ingresso", outbound: "Uscita", hostname: "Hostname primario", defaultLocale: "Locale predefinita", adminBind: "Bind API admin", smtpBind: "Bind SMTP", imapBind: "Bind IMAP", jmapBind: "Bind JMAP", maxMessage: "Dimensione massima messaggio (MB)", tlsMode: "Modalita TLS", passwordLogin: "Login con password", mfa: "MFA richiesta", sessionTimeout: "Timeout sessione (min)", auditRetention: "Conservazione audit (giorni)", aiEnabled: "IA locale abilitata", offlineOnly: "Solo offline", indexing: "Indicizzazione allegati", provider: "Provider", model: "Modello", domainName: "Nome dominio", adminEmail: "Email admin", displayName: "Nome visualizzato", role: "Ruolo", rights: "Riepilogo diritti", permissions: "Permessi", localPart: "Parte locale", quota: "Quota (MB)", source: "Origine", target: "Destinazione", kind: "Tipo", spamEngine: "Motore spam", quarantineRetention: "Conservazione quarantena (giorni)", ruleName: "Nome regola", scope: "Ambito", action: "Azione", searchQuery: "Query", domainList: "Elenco domini", primaryStore: "Storage primario", searchEngine: "Motore di ricerca", replication: "Replica", galVisibility: "Visibilita GAL", directoryKind: "Tipo directory", defaultSieveScript: "Script Sieve predefinito", mailFlowStatus: "Stato consegna", queueOwner: "Proprietario coda", lastAttempt: "Ultimo tentativo", nextAttempt: "Prossimo tentativo", oidcEnabled: "Login OIDC", oidcProviderLabel: "Etichetta provider OIDC", oidcAutoLink: "Collegamento automatico via email", oidcIssuerUrl: "URL issuer OIDC", oidcAuthorizationEndpoint: "Endpoint autorizzazione", oidcTokenEndpoint: "Endpoint token", oidcUserinfoEndpoint: "Endpoint userinfo", oidcClientId: "ID client OIDC", oidcClientSecret: "Secret client OIDC", oidcScopes: "Scopes OIDC", oidcClaimEmail: "Claim email", oidcClaimDisplayName: "Claim nome visualizzato", oidcClaimSubject: "Claim subject"
};

const es: MessageSet = {
  eyebrow: "La Poste Electronique", title: "Consola de administracion", subtitle: "Administracion estructurada para servidor, dominios, anti-spam, auditoria y operaciones.", banner: "Navegacion centrada en servidor y dominio para el plano de control.", languageLabel: "Idioma", refresh: "Actualizar", loading: "Cargando...", noData: "Todavia no hay datos.", saved: "Guardado.", create: "Crear", save: "Guardar", search: "Buscar", enabled: "Habilitado", disabled: "Deshabilitado", close: "Cerrar", open: "Abrir", newItem: "Nuevo", loginTitle: "Inicio de sesion de administrador", loginHelp: "Usa una cuenta de administrador para acceder al plano de control.", login: "Iniciar sesion", logout: "Cerrar sesion", password: "Contrasena", runPstJobs: "Ejecutar trabajos PST pendientes", oidcLogin: "Iniciar sesion con SSO", oidcOrDivider: "o",
  pageServer: "Servidor", pageDomain: "Dominio", pageAntispam: "Anti-spam", pageAudit: "Auditoria", pageOperations: "Operaciones",
  serverTabs: { status: "Estado", server: "Politicas del servidor", security: "Politicas de seguridad", ai: "Politicas de IA local", domains: "Dominios", admins: "Administradores" },
  domainTabs: { overview: "Resumen", accounts: "Cuentas", aliases: "Alias", admins: "Admins" },
  antispamTabs: { content: "Filtrado de contenido", engines: "Motores anti-spam", rules: "Reglas de filtrado", quarantine: "Cuarentena" },
  auditTabs: { journal: "Registro", trace: "Trazado de correo" },
  operationsTabs: { protocols: "Protocolos", storage: "Almacenamiento", mailflow: "Flujo de correo" },
  serverOverview: "Resumen del servidor", protocolStatus: "Estado de protocolos", serverPolicies: "Politicas del servidor", securityPolicies: "Politicas de seguridad", localAiPolicies: "Politicas de IA local", manageDomains: "Gestionar dominios", administrators: "Administradores", adminMatrix: "Derechos admin por dominio", selectedDomain: "Dominio seleccionado", domainPolicySnapshot: "Instantanea de politicas del dominio", domainAccounts: "Cuentas del dominio", domainAliases: "Alias del dominio", domainAdmins: "Administradores del dominio", contentFiltering: "Filtrado de contenido", antispamEngines: "Motores anti-spam", filterRules: "Reglas de filtrado", ruleList: "Lista de reglas", quarantine: "Cuarentena", auditJournal: "Registro de auditoria", emailTrace: "Busqueda de trazado de correo por multiples criterios", storageOverview: "Resumen de almacenamiento", mailFlowMonitor: "Monitor de flujo de correo", mailboxTransfers: "Transferencias PST de buzones", pstImport: "Importar PST", pstExport: "Exportar PST", pstPath: "Ruta PST del servidor", pstFile: "Archivo PST", requestedBy: "Solicitado por", transferHistory: "Historial de transferencias", noTransfers: "Todavia no hay transferencia PST.", mailboxName: "Buzon", accountDetails: "Detalles de la cuenta", newAccount: "Nuevo", newPassword: "Nueva contrasena", primaryMailbox: "Buzon principal", selectAccountHint: "Haz doble clic en una cuenta o usa importar/exportar desde la lista de cuentas.",
  domains: "Dominios", accounts: "Cuentas", aliases: "Alias", queue: "Colas", status: "Estado", defaultQuota: "Cuota predeterminada", inbound: "Entrante", outbound: "Saliente", hostname: "Nombre de host principal", defaultLocale: "Locale predeterminada", adminBind: "Bind de API admin", smtpBind: "Bind SMTP", imapBind: "Bind IMAP", jmapBind: "Bind JMAP", maxMessage: "Tamano maximo del mensaje (MB)", tlsMode: "Modo TLS", passwordLogin: "Inicio con contrasena", mfa: "MFA requerida", sessionTimeout: "Tiempo de sesion (min)", auditRetention: "Retencion de auditoria (dias)", aiEnabled: "IA local habilitada", offlineOnly: "Solo sin conexion", indexing: "Indexacion de adjuntos", provider: "Proveedor", model: "Modelo", domainName: "Nombre de dominio", adminEmail: "Correo admin", displayName: "Nombre visible", role: "Rol", rights: "Resumen de derechos", permissions: "Permisos", localPart: "Parte local", quota: "Cuota (MB)", source: "Origen", target: "Destino", kind: "Tipo", spamEngine: "Motor spam", quarantineRetention: "Retencion de cuarentena (dias)", ruleName: "Nombre de la regla", scope: "Ambito", action: "Accion", searchQuery: "Consulta", domainList: "Lista de dominios", primaryStore: "Almacenamiento principal", searchEngine: "Motor de busqueda", replication: "Replicacion", galVisibility: "Visibilidad GAL", directoryKind: "Tipo de directorio", defaultSieveScript: "Script Sieve predeterminado", mailFlowStatus: "Estado de entrega", queueOwner: "Propietario de la cola", lastAttempt: "Ultimo intento", nextAttempt: "Proximo intento", oidcEnabled: "Inicio OIDC", oidcProviderLabel: "Etiqueta del proveedor OIDC", oidcAutoLink: "Vinculacion automatica por correo", oidcIssuerUrl: "URL issuer OIDC", oidcAuthorizationEndpoint: "Endpoint de autorizacion", oidcTokenEndpoint: "Endpoint de token", oidcUserinfoEndpoint: "Endpoint de userinfo", oidcClientId: "ID de cliente OIDC", oidcClientSecret: "Secreto de cliente OIDC", oidcScopes: "Scopes OIDC", oidcClaimEmail: "Claim de correo", oidcClaimDisplayName: "Claim de nombre visible", oidcClaimSubject: "Claim de subject"
};

export const messages = defineLocaleCatalog(en, { fr, de, it, es });
