import { DEFAULT_PAGE_ID } from "../pages/index.js?v=20260501-health-check-output";

// Browser context shared by the LPE-CT management console entry point.
export const elements = {
  feedback: document.getElementById("feedback"),
  loginFeedback: document.getElementById("login-feedback"),
  loginShell: document.getElementById("login-shell"),
  consoleShell: document.getElementById("console-shell"),
  mainWorkspace: document.getElementById("main-workspace"),
  sidebar: document.getElementById("sidebar"),
  sidebarBackdrop: document.getElementById("sidebar-backdrop"),
  sidebarToggle: document.getElementById("sidebar-toggle"),
  mobileSidebarToggle: document.getElementById("mobile-sidebar-toggle"),
  drawerBackdrop: document.getElementById("drawer-backdrop"),
  drawer: document.getElementById("drawer"),
  drawerTitle: document.getElementById("drawer-title"),
  drawerSummary: document.getElementById("drawer-summary"),
  drawerContent: document.getElementById("drawer-content"),
  drawerClose: document.getElementById("drawer-close"),
  localePickers: Array.from(document.querySelectorAll("[data-locale-picker]")),
  navButtons: Array.from(document.querySelectorAll("[data-nav-button]")),
  pageViews: Array.from(document.querySelectorAll("[data-page-view]")),
  pageTabButtons: Array.from(document.querySelectorAll("[data-action='page-tab']")),
  pageTabPanels: Array.from(document.querySelectorAll("[data-page-tab-panel]")),
  refresh: document.getElementById("refresh"),
  refreshToolbar: document.getElementById("refresh-toolbar"),
  runDigests: document.getElementById("run-digests"),
  loginForm: document.getElementById("login-form"),
  quarantineSearchForm: document.getElementById("quarantine-search-form"),
  historySearchForm: document.getElementById("history-search-form"),
  createAddressRule: document.getElementById("create-address-rule"),
  createAttachmentRule: document.getElementById("create-attachment-rule"),
  editVirusFiltering: document.getElementById("edit-virus-filtering"),
  editFilteringPolicy: document.getElementById("edit-filtering-policy"),
  editRecipientVerification: document.getElementById("edit-recipient-verification"),
  editDkimSettings: document.getElementById("edit-dkim-settings"),
  createDkimDomain: document.getElementById("create-dkim-domain"),
  editDigestSettings: document.getElementById("edit-digest-settings"),
  createDigestDefault: document.getElementById("create-digest-default"),
  createDigestOverride: document.getElementById("create-digest-override"),
  nodeName: document.getElementById("node-name"),
  heroSummary: document.getElementById("hero-summary"),
  statusBadge: document.getElementById("status-badge"),
  upstreamBadge: document.getElementById("upstream-badge"),
  heroPrimaryRelay: document.getElementById("hero-primary-relay"),
  heroRouteSummary: document.getElementById("hero-route-summary"),
  heroReportingSummary: document.getElementById("hero-reporting-summary"),
  heroReportingCopy: document.getElementById("hero-reporting-copy"),
  operatorEmail: document.getElementById("operator-email"),
  operatorRole: document.getElementById("operator-role"),
  contextOperator: document.getElementById("context-operator"),
  contextRole: document.getElementById("context-role"),
  contextVersion: document.getElementById("context-version"),
  contextLicense: document.getElementById("context-license"),
  contextBuild: document.getElementById("context-build"),
  contextTime: document.getElementById("context-time"),
  metricSystemHealth: document.getElementById("metric-system-health"),
  metricInbound: document.getElementById("metric-inbound"),
  metricDeferred: document.getElementById("metric-deferred"),
  metricQuarantine: document.getElementById("metric-quarantine"),
  metricAttempts: document.getElementById("metric-attempts"),
  metricHeld: document.getElementById("metric-held"),
  metricRoutingRules: document.getElementById("metric-routing-rules"),
  metricDkimDomains: document.getElementById("metric-dkim-domains"),
  metricRecipientVerification: document.getElementById("metric-recipient-verification"),
  systemOverviewList: document.getElementById("system-overview-list"),
  queueStatusList: document.getElementById("queue-status-list"),
  scannerStatusList: document.getElementById("scanner-status-list"),
  relayHealthList: document.getElementById("relay-health-list"),
  topSpamRelaysList: document.getElementById("top-spam-relays-list"),
  topVirusRelaysList: document.getElementById("top-virus-relays-list"),
  topVirusesList: document.getElementById("top-viruses-list"),
  scanSummaryList: document.getElementById("scan-summary-list"),
  trafficChart: document.getElementById("traffic-chart"),
  trafficTable: document.getElementById("traffic-table"),
};

export const containers = {
  quarantine: document.getElementById("quarantine-list"),
  history: document.getElementById("history-list"),
  virusFiltering: document.getElementById("virus-filtering-status"),
  filteringPolicy: document.getElementById("filtering-policy-status"),
  addressRules: document.getElementById("address-rules-list"),
  attachmentRules: document.getElementById("attachment-rules-list"),
  recipientVerification: document.getElementById("recipient-verification-status"),
  dkimDomains: document.getElementById("dkim-domain-list"),
  digestSettings: document.getElementById("digest-settings-list"),
  digestDefaults: document.getElementById("digest-defaults-list"),
  digestOverrides: document.getElementById("digest-overrides-list"),
  digestReports: document.getElementById("digest-report-list"),
  systemInformation: document.getElementById("reporting-system-information"),
  platform: document.getElementById("platform-list"),
  mailLog: document.getElementById("mail-log"),
  audit: document.getElementById("audit-log"),
  messageLog: document.getElementById("message-log"),
  emailAlertLog: document.getElementById("email-alert-log"),
};

export const AUTH_TOKEN_KEY = 'lpeCtAdminToken';
export const LAST_ADMIN_EMAIL_KEY = 'lpeCtAdminLastEmail';
export const DASHBOARD_REFRESH_INTERVAL_MS = 60_000;
export const DEFAULT_QUARANTINE_COLUMN_WIDTHS = [112, 220, 220, 280, 172, 112];
export const DEFAULT_HISTORY_COLUMN_WIDTHS = [172, 176, 144, 132, 220, 220, 112];
export const MIN_HISTORY_COLUMN_WIDTH = 88;
export const DEFAULT_LOG_COLUMN_WIDTHS = {
  mail: [56, 280, 172, 112, 132],
  interface: [56, 280, 172, 112, 132],
  messages: [56, 280, 172, 112, 132],
  emailAlerts: [172, 180, 132, 360],
};

// Application State
export const state = {
  dashboard: null,
  quarantine: [],
  history: [],
  routeDiagnostics: null,
  reporting: null,
  digestReports: [],
  systemServices: [],
  policyStatus: null,
  hostLogs: {
    mail: [],
    interface: [],
    messages: [],
  },
  selectedTrace: null,
  pageTabs: {
    filtering: "content-filtering",
    "anti-spam": "settings",
    quarantine: "search",
    reporting: "system-information",
    logs: "interface",
  },
  systemSetup: {
    primaryTab: "network",
    nestedTabs: {
      network: "ip",
      mailRelay: "general",
      mailAuthentication: "spf",
    },
  },
  hostClockLoadedAt: null,
  loading: {
    dashboard: false,
    ops: false,
    auth: false,
    trace: false,
    runDigests: false,
  },
  activePage: DEFAULT_PAGE_ID,
  historySort: {
    key: "date",
    direction: "desc",
  },
  quarantineSort: {
    key: "date",
    direction: "desc",
  },
  quarantineSelection: new Set(),
  quarantineDialogTab: "details",
  historyColumnWidths: [...DEFAULT_HISTORY_COLUMN_WIDTHS],
  logTables: Object.fromEntries(
    Object.entries(DEFAULT_LOG_COLUMN_WIDTHS).map(([key, widths]) => [
      key,
      {
        sort: { key: "date", direction: "desc" },
        columnWidths: [...widths],
      },
    ]),
  ),
  drawer: {
    open: false,
    previousFocus: null,
    onClose: null,
  },
};
