ALTER TABLE calendar_events
    ADD COLUMN IF NOT EXISTS time_zone TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS duration_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS recurrence_rule TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS attendees_json TEXT NOT NULL DEFAULT '[]';
